// <auto-generated />
using System;
using MachineryManagerEnterprise.Usage.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Usage.Infrastructure.Migrations
{
    [DbContext(typeof(UsageDbContext))]
    [Migration("20261002192000_InitialUsageSchema")]
    partial class InitialUsageSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("usage")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineryManagerEnterprise.SharedKernel.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HoldingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AuditEntry", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MachineryManagerEnterprise.Usage.Infrastructure.Persistence.UsageCapSetting", b =>
                {
                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DefaultDailyCap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Unit");

                    b.ToTable("UsageCapSetting", "usage");

                    b.HasData(
                        new
                        {
                            Unit = "Hour",
                            DefaultDailyCap = 24m
                        },
                        new
                        {
                            Unit = "Kilometer",
                            DefaultDailyCap = 1000m
                        },
                        new
                        {
                            Unit = "Mile",
                            DefaultDailyCap = 1000m
                        });
                });

            modelBuilder.Entity("Usage.Domain.MeterDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DailyCapOverride")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("MeterDevice", "usage");
                });

            modelBuilder.Entity("Usage.Domain.UsageLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("FrozenUpToDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerType", "OwnerId", "Unit")
                        .IsUnique();

                    b.ToTable("UsageLedger", "usage");
                });

            modelBuilder.Entity("Usage.Domain.UsageLedger", b =>
                {
                    b.OwnsMany("Usage.Domain.UsageEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("EntryDate")
                                .HasColumnType("date");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<decimal>("OperationalUsageAmount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid?>("OperatorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("RawReadingValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int");

                            b1.Property<TimeOnly?>("ShiftEndTime")
                                .HasColumnType("time");

                            b1.Property<int?>("ShiftIndex")
                                .HasColumnType("int");

                            b1.Property<TimeOnly?>("ShiftStartTime")
                                .HasColumnType("time");

                            b1.Property<Guid>("SourceMeterDeviceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UsageLedgerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjectId");

                            b1.HasIndex("SourceMeterDeviceId");

                            b1.HasIndex("UsageLedgerId", "Sequence")
                                .IsUnique();

                            b1.HasIndex("UsageLedgerId", "EntryDate", "ShiftIndex")
                                .IsUnique()
                                .HasFilter("[ShiftIndex] IS NOT NULL");

                            b1.ToTable("UsageEntry", "usage");

                            b1.WithOwner()
                                .HasForeignKey("UsageLedgerId");
                        });

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
