<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>MachineryManager.Administration.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Administration.Application\Administration.Application.csproj" />
    <ProjectReference Include="..\Administration.Domain\Administration.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
  </ItemGroup>

</Project>