<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Castle.Core" /> <!-- Explicit ref: see note in Directory.Packages.props -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Modules\Configuration\Configuration.Application\Configuration.Application.csproj" />
  </ItemGroup>

</Project>
