<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Organization.Application\Organization.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
  </ItemGroup>

</Project>
