<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MachineryManagerEnterprise.Administration.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Administration.Domain\Administration.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="MediatR" />
  <PackageReference Include="FluentValidation" />
  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  <PackageReference Include="Mapster" />
  <PackageReference Include="Mapster.DependencyInjection" />
</ItemGroup>

</Project>