// <auto-generated />
using System;
using MachineryManagerEnterprise.Personnel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Personnel.Infrastructure.Migrations
{
    [DbContext(typeof(PersonnelDbContext))]
    [Migration("20260912214127_InitialPersonnelSchema")]
    partial class InitialPersonnelSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("personnel")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MachineryManagerEnterprise.Personnel.Domain.Personnel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("JobTitleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonnelCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentProjectId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "PersonnelCode")
                        .IsUnique();

                    b.ToTable("Personnel", "personnel");
                });

            modelBuilder.Entity("MachineryManagerEnterprise.SharedKernel.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HoldingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AuditEntry", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MachineryManagerEnterprise.Personnel.Domain.Personnel", b =>
                {
                    b.OwnsMany("MachineryManagerEnterprise.Personnel.Domain.PersonnelDrivingLicense", "DrivingLicenses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("DrivingLicenseTypeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("ExpiryDate")
                                .HasColumnType("date");

                            b1.Property<Guid>("PersonnelId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("PersonnelId", "DrivingLicenseTypeId")
                                .IsUnique();

                            b1.ToTable("PersonnelDrivingLicense", "personnel");

                            b1.WithOwner()
                                .HasForeignKey("PersonnelId");
                        });

                    b.Navigation("DrivingLicenses");
                });
#pragma warning restore 612, 618
        }
    }
}
