<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>MachineryManager.AuditLog.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuditLog.Application\AuditLog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>


</Project>