// <auto-generated />
using System;
using System.Collections.Generic;
using MachineryManager.Administration.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Administration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdministrationDbContext))]
    [Migration("20260820222811_InitialAdministrationSchema")]
    partial class InitialAdministrationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("administration")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Administration.Domain.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profile", "administration");
                });

            modelBuilder.Entity("Administration.Domain.UserProfileAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Scope", "Administration.Domain.UserProfileAssignment.Scope#AuthorizationScope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid?>("HoldingId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ScopeHoldingId");

                            b1.Property<int>("Level")
                                .HasColumnType("int")
                                .HasColumnName("ScopeLevel");

                            b1.Property<Guid?>("OrganizationId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ScopeOrganizationId");

                            b1.Property<Guid?>("ProjectId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("ScopeProjectId");
                        });

                    b.HasKey("Id");

                    b.ToTable("UserProfileAssignment", "administration");
                });
#pragma warning restore 612, 618
        }
    }
}
