// <auto-generated />
using System;
using MachineryManagerEnterprise.WorkCalendar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WorkCalendar.Infrastructure.Migrations
{
    [DbContext(typeof(WorkCalendarDbContext))]
    partial class WorkCalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workcalendar")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkCalendar.Domain.WorkCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("WorkCalendar", "workcalendar");
                });

            modelBuilder.Entity("WorkCalendar.Domain.WorkCalendar", b =>
                {
                    b.OwnsMany("WorkCalendar.Domain.DayOverride", "DayOverrides", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CustomSchedule")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CustomSchedule");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<bool>("IsCancelled")
                                .HasColumnType("bit");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("WorkCalendarId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkCalendarId");

                            b1.ToTable("DayOverride", "workcalendar");

                            b1.WithOwner()
                                .HasForeignKey("WorkCalendarId");
                        });

                    b.OwnsMany("WorkCalendar.Domain.WorkPattern", "WorkPatterns", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("EndDate")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<Guid>("WorkCalendarId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("_weeklySchedule")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("WeeklySchedule");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkCalendarId");

                            b1.ToTable("WorkPattern", "workcalendar");

                            b1.WithOwner()
                                .HasForeignKey("WorkCalendarId");
                        });

                    b.Navigation("DayOverrides");

                    b.Navigation("WorkPatterns");
                });
#pragma warning restore 612, 618
        }
    }
}
